irregular_verbs = {
    "ir": {
        "present": ["voy", "vas", "va", "vamos", "vais", "van"],
        "preterite": ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
        "imperfect": ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
        "present_subjunctive": ["vaya", "vayas", "vaya", "vayamos", "vayáis",
                                "vayan"],
        "imperfect_subjunctive_ra": ["fuera", "fueras", "fuera", "fuéramos",
                                     "fuerais", "fueran"],
        "imperfect_subjunctive_se": ["fuese", "fueses", "fuese", "fuésemos",
                                     "fueseis", "fuesen"],
        "affirmative_imperative": [None, "ve", "vaya", "vayamos", "id",
                                   "vayan"],
        "negative_imperative": [None, "no vayas", "no vaya", "no vayamos",
                                "no vayáis", "no vayan"],
        "participles": ["yendo", "ido"]
    },
    "ser": {
        "present": ["soy", "eres", "es", "somos", "sois", "son"],
        "preterite": ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
        "imperfect": ["era", "eras", "era", "éramos", "erais", "eran"],
        "present_subjunctive": ["sea", "seas", "sea", "seamos", "seáis",
                                "sean"],
        "imperfect_subjunctive_ra": ["fuera", "fueras", "fuera", "fuéramos",
                                     "fuerais", "fueran"],
        "imperfect_subjunctive_se": ["fuese", "fueses", "fuese", "fuésemos",
                                     "fueseis", "fuesen"],
        "affirmative_imperative": [None, "sé", "sea", "seamos", "sed", "sean"],
        "negative_imperative": [None, "no seas", "no sea", "no seamos",
                                "no seáis", "no sean"]
    },
    "estar": {
        "present": ["estoy", "estás", "está", "estamos", "estáis", "están"],
        "preterite": ["estuve", "estuviste", "estuvo", "estuvimos",
                      "estuvisteis", "estuvieron"],
        "present_subjunctive": ["esté", "estés", "esté", "estemos", "estéis",
                                "estén"],
        "imperfect_subjunctive_ra": ["estuviera", "estuvieras", "estuviera",
                                     "estuviéramos", "estuvierais",
                                     "estuvieran"],
        "imperfect_subjunctive_se": ["estuviese", "estuvieses", "estuviese",
                                     "estuviésemos", "estuvieseis",
                                     "estuviesen"],
        "affirmative_imperative": [None, "está", "esté", "estemos", "estad",
                                   "estén"],
        "negative_imperative": [None, "no estés", "no esté", "no estemos",
                                "no estéis", "no estén"]
    },
    "hacer": {
        "present": ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
        "preterite": ["hice", "hiciste", "hizo", "hicimos", "hicisteis",
                      "hicieron"],
        "conditional": ["haría", "harías", "haría", "haríamos", "haríais",
                        "harían"],
        "future": ["haré", "harás", "hará", "haremos", "haréis", "harán"],
        "present_subjunctive": ["haga", "hagas", "haga", "hagamos", "hagáis",
                                "hagan"],
        "imperfect_subjunctive_ra": ["hiciera", "hicieras", "hiciera",
                                     "hiciéramos", "hicierais", "hicieran"],
        "imperfect_subjunctive_se": ["hiciese", "hicieses", "hiciese",
                                     "hiciésemos", "hicieseis", "hiciesen", ],
        "affirmative_imperative": [None, "haz", "haga", "hagamos", "haced",
                                   "hagan"],
        "negative_imperative": [None, "no hagas", "no haga", "no hagamos",
                                "no hagáis", "no hagan"],
        "participles": ["haciendo", "hecho"]
    },
    "decir": {
        "present": ["digo", "dices", "dice", "decimos", "decís", "dicen"],
        "preterite": ["dije", "dijiste", "dijo", "dijimos", "dijisteis",
                      "dijeron"],
        "conditional": ["diría", "dirías", "diría", "diríamos", "diríais",
                        "dirían"],
        "future": ["diré", "dirás", "dirá", "diremos", "diréis", "dirán"],
        "present_subjunctive": ["diga", "digas", "diga", "digamos", "digáis",
                                "digan"],
        "imperfect_subjunctive_ra": ["dijera", "dijeras", "dijera",
                                     "dijéramos", "dijerais", "dijeran"],
        "imperfect_subjunctive_se": ["dijese", "dijeses", "dijese",
                                     "dijésemos", "dijeseis", "dijesen"],
        "affirmative_imperative": [None, "di", "diga", "digamos", "decid",
                                   "digan"],
        "negative_imperative": [None, "no digas", "no diga", "no digamos",
                                "no digáis", "no digan"],
        "participles": ["diciendo", "dicho"]
    }
}
